### ISSUE TITLE
Laravel 8.x support

### ISSUE THREAD

**Issue by davi5e** [skydiver/nova-update-card#17] opened 2020-09-24 03:20 UTC
Should be a simple change to [guzzlehttp/guzzle](https://github.com/guzzle/guzzle) `^7.0.1` as a requirement.

**Comment by skydiver** [comment] 2020-09-24 18:12
hey @davi5e, the problem is related to `knplabs/packagist-api` dependency, is still using an old version of guzzle.
I'm gonna replace the package and manually fetch the laravel version...

**Comment by skydiver** [comment] 2020-09-24 22:55
@davi5e fixed on v1.5.0 🎆

**Closed as completed** 2020-09-25 13:28 UTC
